name: Bug report
description: File a bug in ShipGuard
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes: { value: "Thanks for the report." }
  - type: input
    id: summary
    attributes: { label: Summary, description: "What went wrong?" }
    validations: { required: true }
  - type: textarea
    id: steps
    attributes: { label: Steps to reproduce, description: "List steps and any sample data." }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Expected behavior }
    validations: { required: true }
  - type: textarea
    id: logs
    attributes: { label: Logs, description: "Paste logs or errors." }
    validations: { required: false }
