name: Feature request
description: Suggest an idea for ShipGuard
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes: { value: "Tell us what would improve ShipGuard." }
  - type: textarea
    id: problem
    attributes: { label: Problem statement, description: "What problem are you trying to solve?" }
    validations: { required: true }
  - type: textarea
    id: proposal
    attributes: { label: Proposed solution, description: "Describe the behavior you want." }
    validations: { required: true }
  - type: textarea
    id: alternatives
    attributes: { label: Alternatives, description: "Any alternatives considered?" }
    validations: { required: false }
